### PR TITLE
Django 1.8 compliant

### PR DESCRIPTION
**Pull request by gpichot**
Added exclude parameter to forms Meta classes for 1.8 compliance.

### CODE REVIEW

**Comment by lfalvarez** [comment]
I just tested this branch in a Django==1.7.x and it works like a charm. :+1:

**Comment by eriktelepovsky** [comment]
Great. Merging ;)

**Comment by merwok** [comment]
This is great!  Is a release planned?

**Comment by eriktelepovsky** [comment]
Right now. Sorry for delay.

**Comment by merwok** [comment]
I was going to make my requirements file get the master from github, and now I don’t have to.  Thanks a lot!

**Pull request merged**
